volumes:
  db_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    depends_on:
      - db
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
  frontend:
    container_name: foodgram-frontend
    build: ./frontend/
    volumes:
      - ./frontend/:/app/result_build/
  gateway:
    container_name: foodgram-gateway
    image: dean7773/foodgram_gateway
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/media/
